### PR TITLE
Fix mercurial init/pull/update and hgrc template

### PR DESCRIPTION
**Pull request by cedk**
Add also some tests based on a dummy bitbucket repository.

### CODE REVIEW

**Comment by tboerger** [comment]
Pretty cool to get it in a working state again, but why don't you clone a repo instead of initializing it how you are doing it now?

**Comment by bradrydzewski** [comment]
@tboerger I'm not a mercurial expert by any means, but I'm guessing this is to play nicely with caching.

**Comment by cedk** [comment]
Like that it can be reused if the directory is stored for some cache reuse.
I looked at the drone-git pluggin.

**Comment by tboerger** [comment]
Ah, sorry... I missed that the git plugin also does it that way :)
LGTM

**Comment by bradrydzewski** [comment]
LGTM as well, thanks!

**Comment by tboerger** [comment]
@bradrydzewski you have to add your docker username to your .drone.sec blueprint ;)

**Comment by cedk** [comment]
@bradrydzewski is it possible to fix the build process to get the image publish?
http://beta.drone.io/drone-plugins/drone-hg/3
Thanks.

**Pull request merged**
